build:
  flake8:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install flake8
      - flake8 wagtailmedia
  isort:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .[testing]
      - isort --check-only --diff --recursive wagtailmedia
  unittest:
    image: python:3.5
    commands:
      - XDG_CACHE_HOME=/drone/pip-cache pip install -e .[testing,docs]
      - python runtests.py

cache:
  mount:
    - node_modules
    - /drone/pip-cache
